### ISSUE TITLE
There's an unknown Unicode character in the description for "GetTrackMIDILyrics"

### ISSUE THREAD

**Issue by GavinRay97** [justinfrankel/reaper-sdk#2]
I only found this out by accident, was programmatically parsing the header with something and tool froze.
Removed and replaced parts of the header + re-ran until had narrowed it down.

Not sure if you care but just a heads up =)

https://github.com/justinfrankel/reaper-sdk/blob/ec0c1dc1655eb6a192fa7a22c2258a38a5ebbe9c/sdk/reaper_plugin_functions.h#L3160

![image](https://user-images.githubusercontent.com/26604994/113522893-2ab13900-9572-11eb-8a81-0bdd5acd29b6.png)

**Comment by justinfrankel** [comment]
Fixing, thanks!
